INSERT INTO CURRENCY (MULTIPLIER, SYMBOL)
VALUES (100, 'BGN'),
       (100, 'RON');

INSERT INTO TAX_SCHEME (NAME)
VALUES ('BG_VAT'),
       ('RO_VAT');

INSERT INTO TAX_CATEGORY (PERCENT, NAME)
VALUES (9, 'VAT_9'),
       (19, 'VAT_19'),
       (20, 'VAT_20');

INSERT INTO TAX_SCHEME_TAX_CATEGORIES (TAX_CATEGORIES_NAME, TAX_SCHEME_NAME)
VALUES ('VAT_19', 'RO_VAT'),
       ('VAT_20', 'BG_VAT'),
       ('VAT_9', 'BG_VAT'),
       ('VAT_9', 'RO_VAT');

INSERT INTO MARKET (CURRENCY_SYMBOL, NAME, TAX_SCHEME_NAME)
VALUES ('BGN', 'BG', 'BG_VAT'),
       ('RON', 'RO', 'RO_VAT');

INSERT INTO STORE (MARKET_NAME, NAME)
VALUES ('RO', 'ELECT.RO'),
       ('RO', 'FRESH.RO'),
       ('BG', 'ELECT.BG');

INSERT INTO STORE_SECTION (STORE_NAME, DESCRIPTION, NAME)
VALUES ('ELECT.RO', 'Descriere atractivă a categoriei electronice', 'Electronice'),
       ('ELECT.BG', 'Атрактивно описание на категория електроника', 'Електронен'),
       ('FRESH.RO', 'Descriere generică a secțiunii aprozar', 'Aprozar');

INSERT INTO PRODUCT_CATEGORY (DESCRIPTION, NAME)
VALUES ('Descriere comercială pentru telefoane mobile', 'Telefoane Mobile'),
       ('Fructe proaspete', 'Fructe');

INSERT INTO PRODUCT (DESCRIPTION, NAME)
values ('Samsung S24 Mobile Phone', 'Samsung S24'),
       ('Mere Granny Smith', 'Mere Verzi');

INSERT INTO STORE_SECTION_ENTRY (PRICE, PRODUCT_ID, STORE_SECTION_ID, TAX_CATEGORY_NAME)
VALUES (389999, (SELECT ID FROM PRODUCT WHERE NAME = 'Samsung S24'),
        (SELECT ID FROM STORE_SECTION WHERE NAME = 'Electronice'), 'VAT_19');

INSERT INTO STORE_SECTION_ENTRY (PRICE, PRODUCT_ID, STORE_SECTION_ID, TAX_CATEGORY_NAME)
VALUES (152758, (SELECT ID FROM PRODUCT WHERE NAME = 'Samsung S24'),
        (SELECT ID FROM STORE_SECTION WHERE NAME = 'Електронен'), 'VAT_20');

INSERT INTO STORE_SECTION_ENTRY (PRICE, PRODUCT_ID, STORE_SECTION_ID, TAX_CATEGORY_NAME)
VALUES (1299, (SELECT ID FROM PRODUCT WHERE NAME = 'Mere Verzi'),
        (SELECT ID FROM STORE_SECTION WHERE NAME = 'Aprozar'), 'VAT_9');
