create table currency
(
    multiplier integer,
    id         bigint generated by default as identity,
    symbol     varchar(255),
    primary key (id)
);
create table market
(
    currency_id   bigint unique,
    id            bigint generated by default as identity,
    tax_scheme_id bigint unique,
    primary key (id)
);
create table product
(
    id          bigint generated by default as identity,
    description varchar(255),
    name        varchar(255),
    primary key (id)
);
create table product_categories
(
    categories_id bigint not null,
    product_id    bigint not null,
    primary key (categories_id, product_id)
);
create table product_category
(
    id          bigint generated by default as identity,
    description varchar(255),
    name        varchar(255),
    primary key (id)
);
create table store
(
    id        bigint generated by default as identity,
    market_id bigint unique,
    primary key (id)
);
create table store_section
(
    id          bigint generated by default as identity,
    description varchar(255),
    name        varchar(255),
    primary key (id)
);
create table store_section_entry
(
    price           integer,
    id              bigint generated by default as identity,
    product_id      bigint,
    section_id      bigint,
    tax_category_id bigint,
    primary key (id)
);
create table tax_category
(
    percent integer,
    id      bigint generated by default as identity,
    name    varchar(255),
    primary key (id)
);
create table tax_scheme
(
    id bigint generated by default as identity,
    primary key (id)
);
create table tax_scheme_tax_categories
(
    tax_categories_id bigint not null unique,
    tax_scheme_id     bigint not null,
    primary key (tax_categories_id, tax_scheme_id)
);
alter table if exists market
    add constraint FK1amj15xaii8i3nj1nvn47k9s0 foreign key (currency_id) references currency;
alter table if exists market
    add constraint FKrbpr3pqicqnoiqcp3kvre5yjq foreign key (tax_scheme_id) references tax_scheme;
alter table if exists product_categories
    add constraint FKg17eropvif2jlfu993ngjkxbl foreign key (categories_id) references product_category;
alter table if exists product_categories
    add constraint FKppc5s0f38pgb35a32dlgyhorc foreign key (product_id) references product;
alter table if exists store
    add constraint FKr8sqanx5snrn03vrwnonlklfk foreign key (market_id) references market;
alter table if exists store_section_entry
    add constraint FKfmals3b8y0s6rwqp6vgijjpje foreign key (section_id) references store_section;
alter table if exists store_section_entry
    add constraint FK8odhvbjt7vmbh49ayxv145fda foreign key (product_id) references product;
alter table if exists store_section_entry
    add constraint FK1g0ha0ntgmc42amxi4mq0jegc foreign key (tax_category_id) references tax_category;
alter table if exists tax_scheme_tax_categories
    add constraint FKrkxb2wn5nvsnhri7wb4hkvd4g foreign key (tax_categories_id) references tax_category;
alter table if exists tax_scheme_tax_categories
    add constraint FKa0pwn4qoevs2oolykb6maocp3 foreign key (tax_scheme_id) references tax_scheme;