###
POST http://localhost:8080/api/v1/manage/set-price
Authorization: Basic dXNlcjpwYXNzd29yZA==
Content-Type: application/json

{"productId":1, "storeSectionId":1, "price": 419999}

###
GET http://localhost:8080/api/v1/browse/markets
Authorization: Basic dXNlcjpwYXNzd29yZA==



###
GET http://localhost:8080/api/v1/manage/set-price
Authorization: Basic dXNlcjpwYXNzd29yZA==


###
GET http://localhost:8080/api/v1/browse/markets
#Authorization: Basic dXNlcjpwYXNzd29yZA==
Accept: application/json

###
GET http://localhost:8080/api/v1/browse/markets
Accept: application/json
